# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-12-20 13:54
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='新闻详情'),
        ),
    ]
