# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-12-09 16:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='送料机名称')),
                ('category', models.CharField(default='', max_length=20, verbose_name='送料机类别')),
                ('tag', models.CharField(default='', max_length=10, verbose_name='送料机标签')),
                ('desc', models.CharField(default='', max_length=300, verbose_name='送料机描述')),
                ('detail', models.TextField(verbose_name='送料机详情')),
                ('image', models.ImageField(default='', upload_to='product/', verbose_name='送料机图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '送料机',
                'verbose_name_plural': '送料机',
            },
        ),
        migrations.CreateModel(
            name='ProductSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='送料机系列名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '送料机系列',
                'verbose_name_plural': '送料机系列',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductSeries', verbose_name='送料机系列'),
        ),
    ]
