# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-12-09 16:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='视频名称')),
                ('url', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='视频访问地址')),
                ('video', models.FileField(default='', upload_to='video/', verbose_name='视频上传')),
                ('video_times', models.IntegerField(default=0, verbose_name='视频时长(分钟数)')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='送料机')),
                ('product_series', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.ProductSeries', verbose_name='送料机系列')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
    ]
