# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-12-11 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='product_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductSeries', verbose_name='送料机系列'),
        ),
    ]
